#pragma once

#define OFFSET_KSP  0
#define OFFSET_KGP  8
#define OFFSET_KTP  16

#define OFFSET_ZERO 32
#define OFFSET_RA   40
#define OFFSET_SP   48
#define OFFSET_GP   56
#define OFFSET_TP   64
#define OFFSET_T0   72
#define OFFSET_T1   80
#define OFFSET_T2   88
#define OFFSET_S0   96
#define OFFSET_S1   104
#define OFFSET_A0   112
#define OFFSET_A1   120
#define OFFSET_A2   128
#define OFFSET_A3   136
#define OFFSET_A4   144
#define OFFSET_A5   152
#define OFFSET_A6   160
#define OFFSET_A7   168
#define OFFSET_S2   176
#define OFFSET_S3   184
#define OFFSET_S4   192
#define OFFSET_S5   200
#define OFFSET_S6   208
#define OFFSET_S7   216
#define OFFSET_S8   224
#define OFFSET_S9   232
#define OFFSET_S10  240
#define OFFSET_S11  248
#define OFFSET_T3   256
#define OFFSET_T4   264
#define OFFSET_T5   272
#define OFFSET_T6   280
#define OFFSET_F    288

#define OFFSET_UEPC   544
#define OFFSET_UCAUSE 552
#define OFFSET_UTVAL  560
#define OFFSET_DFREN  568

#define OFFSET_MEMCFG        576
#define OFFSET_MEMBOUND0LO   (OFFSET_MEMCFG + 8 * 1)
#define OFFSET_MEMBOUND0HI   (OFFSET_MEMCFG + 8 * 2)
#define OFFSET_MEMBOUND1LO   (OFFSET_MEMCFG + 8 * 3)
#define OFFSET_MEMBOUND1HI   (OFFSET_MEMCFG + 8 * 4)
#define OFFSET_MEMBOUND2LO   (OFFSET_MEMCFG + 8 * 5)
#define OFFSET_MEMBOUND2HI   (OFFSET_MEMCFG + 8 * 6)
#define OFFSET_MEMBOUND3LO   (OFFSET_MEMCFG + 8 * 7)
#define OFFSET_MEMBOUND3HI   (OFFSET_MEMCFG + 8 * 8)
#define OFFSET_MEMBOUND4LO   (OFFSET_MEMCFG + 8 * 9)
#define OFFSET_MEMBOUND4HI   (OFFSET_MEMCFG + 8 * 10)
#define OFFSET_MEMBOUND5LO   (OFFSET_MEMCFG + 8 * 11)
#define OFFSET_MEMBOUND5HI   (OFFSET_MEMCFG + 8 * 12)
#define OFFSET_MEMBOUND6LO   (OFFSET_MEMCFG + 8 * 13)
#define OFFSET_MEMBOUND6HI   (OFFSET_MEMCFG + 8 * 14)
#define OFFSET_MEMBOUND7LO   (OFFSET_MEMCFG + 8 * 15)
#define OFFSET_MEMBOUND7HI   (OFFSET_MEMCFG + 8 * 16)
#define OFFSET_MEMBOUND8LO   (OFFSET_MEMCFG + 8 * 17)
#define OFFSET_MEMBOUND8HI   (OFFSET_MEMCFG + 8 * 18)
#define OFFSET_MEMBOUND9LO   (OFFSET_MEMCFG + 8 * 19)
#define OFFSET_MEMBOUND9HI   (OFFSET_MEMCFG + 8 * 20)
#define OFFSET_MEMBOUND10LO  (OFFSET_MEMCFG + 8 * 21)
#define OFFSET_MEMBOUND10HI  (OFFSET_MEMCFG + 8 * 22)
#define OFFSET_MEMBOUND11LO  (OFFSET_MEMCFG + 8 * 23)
#define OFFSET_MEMBOUND11HI  (OFFSET_MEMCFG + 8 * 24)
#define OFFSET_MEMBOUND12LO  (OFFSET_MEMCFG + 8 * 25)
#define OFFSET_MEMBOUND12HI  (OFFSET_MEMCFG + 8 * 26)
#define OFFSET_MEMBOUND13LO  (OFFSET_MEMCFG + 8 * 27)
#define OFFSET_MEMBOUND13HI  (OFFSET_MEMCFG + 8 * 28)
#define OFFSET_MEMBOUND14LO  (OFFSET_MEMCFG + 8 * 29)
#define OFFSET_MEMBOUND14HI  (OFFSET_MEMCFG + 8 * 30)
#define OFFSET_MEMBOUND15LO  (OFFSET_MEMCFG + 8 * 31)
#define OFFSET_MEMBOUND15HI  (OFFSET_MEMCFG + 8 * 32)

#define OFFSET_JMPCFG        (OFFSET_MEMBOUND15HI + 8)
#define OFFSET_JMPBOUND0LO   (OFFSET_JMPCFG + 8 * 1)
#define OFFSET_JMPBOUND0HI   (OFFSET_JMPCFG + 8 * 2)
#define OFFSET_JMPBOUND1LO   (OFFSET_JMPCFG + 8 * 3)
#define OFFSET_JMPBOUND1HI   (OFFSET_JMPCFG + 8 * 4)
#define OFFSET_JMPBOUND2LO   (OFFSET_JMPCFG + 8 * 5)
#define OFFSET_JMPBOUND2HI   (OFFSET_JMPCFG + 8 * 6)
#define OFFSET_JMPBOUND3LO   (OFFSET_JMPCFG + 8 * 7)
#define OFFSET_JMPBOUND3HI   (OFFSET_JMPCFG + 8 * 8)


#define CONTEXT_RA 0
#define CONTEXT_SP 8
#define CONTEXT_S0 16
#define CONTEXT_S1 24
#define CONTEXT_S2 32
#define CONTEXT_S3 40
#define CONTEXT_S4 48
#define CONTEXT_S5 56
#define CONTEXT_S6 64
#define CONTEXT_S7 72
#define CONTEXT_S8 80
#define CONTEXT_S9 88
#define CONTEXT_S10 96
#define CONTEXT_S11 104